/**
 * distributed_worker — generic per-device process for multi-card kernels.
 *
 * Uses PlatformBackend (onboard or sim) for device/memory/communication ops,
 * then delegates kernel execution to simpler's runtime via dlopen.
 *
 * All case-specific logic (buffer layout, data, verification) is driven by
 * CLI arguments generated by the Python DistributedRunner.
 *
 * Exit codes:
 *   0 — success
 *   1 — argument error
 *   2 — dlopen / dlsym / artifact error
 *   3 — platform / communication error
 *   4 — simpler runtime error
 */

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <dlfcn.h>
#include <fstream>
#include <string>
#include <vector>

#include "platform_backend.h"

// ============================================================================
// Buffer / kernel descriptors + helpers (case-agnostic)
// ============================================================================

struct BufferDesc {
    std::string name;
    std::string dtype;
    size_t count = 0;
    std::string placement; // "window" or "device"
    void *dev_ptr = nullptr;

    size_t elem_size() const {
        if (dtype == "float32" || dtype == "int32" || dtype == "uint32") return 4;
        if (dtype == "float16" || dtype == "int16" || dtype == "uint16") return 2;
        if (dtype == "int64" || dtype == "uint64" || dtype == "float64") return 8;
        if (dtype == "int8" || dtype == "uint8") return 1;
        return 4;
    }
    size_t bytes() const { return count * elem_size(); }
};

struct KernelBinDesc {
    int func_id;
    std::string filename;
};

static BufferDesc parse_buffer_spec(const std::string &spec) {
    BufferDesc b;
    size_t p1 = spec.find(':');
    size_t p2 = spec.find(':', p1 + 1);
    b.name = spec.substr(0, p1);
    b.dtype = spec.substr(p1 + 1, p2 - p1 - 1);
    b.count = static_cast<size_t>(std::atoll(spec.substr(p2 + 1).c_str()));
    return b;
}

static KernelBinDesc parse_kernel_spec(const std::string &spec) {
    size_t p = spec.find(':');
    KernelBinDesc k;
    k.func_id = std::atoi(spec.substr(0, p).c_str());
    k.filename = spec.substr(p + 1);
    return k;
}

static inline void *WindowAlloc(uint64_t windowBase, size_t &offset, size_t bytes) {
    void *ptr = reinterpret_cast<void *>(windowBase + offset);
    offset += bytes;
    return ptr;
}

using fn_get_runtime_size_t = size_t (*)();
using fn_set_device_t = int (*)(int);
using fn_init_runtime_t = int (*)(void*,
    const uint8_t*, size_t, const char*,
    uint64_t*, int, int*, uint64_t*,
    const int*, const uint8_t* const*, const size_t*, int);
using fn_launch_runtime_t = int (*)(void*,
    int, int, int,
    const uint8_t*, size_t,
    const uint8_t*, size_t,
    int);
using fn_finalize_runtime_t = int (*)(void*);

static std::vector<uint8_t> read_file(const std::string& path) {
    std::ifstream f(path, std::ios::binary | std::ios::ate);
    if (!f) return {};
    auto sz = f.tellg();
    f.seekg(0);
    std::vector<uint8_t> buf(static_cast<size_t>(sz));
    f.read(reinterpret_cast<char*>(buf.data()), sz);
    return buf;
}

static bool write_file(const std::string& path, const void* data, size_t size) {
    std::ofstream f(path, std::ios::binary);
    if (!f) return false;
    f.write(reinterpret_cast<const char*>(data), static_cast<std::streamsize>(size));
    return f.good();
}

// ============================================================================
// main
// ============================================================================

int main(int argc, char** argv) {
    int device_id = -1;
    int rank = -1;
    int nranks = -1;
    int root = 0;
    std::string artifact_dir;
    std::string rootinfo_file;
    std::string orch_func;
    std::string orch_file;
    std::string data_dir;
    size_t win_sync_prefix = 0;
    int aicpu_thread_num = 1;
    int block_dim = 1;
    int orch_thread_num = 0;

    std::vector<BufferDesc> buffers;
    std::vector<std::string> load_names;
    std::vector<std::string> save_names;
    std::vector<std::string> arg_tokens;
    std::vector<KernelBinDesc> kernel_bins;
    std::vector<std::pair<std::string,std::string>> env_vars;

    for (int i = 1; i < argc; i++) {
        std::string a(argv[i]);
        if (a == "--device-id" && i + 1 < argc) {
            device_id = std::atoi(argv[++i]);
        } else if (a == "--rank" && i + 1 < argc) {
            rank = std::atoi(argv[++i]);
        } else if (a == "--nranks" && i + 1 < argc) {
            nranks = std::atoi(argv[++i]);
        } else if (a == "--root" && i + 1 < argc) {
            root = std::atoi(argv[++i]);
        } else if (a == "--artifact-dir" && i + 1 < argc) {
            artifact_dir = argv[++i];
        } else if (a == "--rootinfo-file" && i + 1 < argc) {
            rootinfo_file = argv[++i];
        } else if (a == "--orch-func" && i + 1 < argc) {
            orch_func = argv[++i];
        } else if (a == "--orch-file" && i + 1 < argc) {
            orch_file = argv[++i];
        } else if (a == "--data-dir" && i + 1 < argc) {
            data_dir = argv[++i];
        } else if (a == "--win-sync-prefix" && i + 1 < argc) {
            win_sync_prefix = static_cast<size_t>(std::atoll(argv[++i]));
        } else if (a == "--win-buffer" && i + 1 < argc) {
            auto b = parse_buffer_spec(argv[++i]);
            b.placement = "window";
            buffers.push_back(std::move(b));
        } else if (a == "--dev-buffer" && i + 1 < argc) {
            auto b = parse_buffer_spec(argv[++i]);
            b.placement = "device";
            buffers.push_back(std::move(b));
        } else if (a == "--load" && i + 1 < argc) {
            load_names.emplace_back(argv[++i]);
        } else if (a == "--save" && i + 1 < argc) {
            save_names.emplace_back(argv[++i]);
        } else if (a == "--arg" && i + 1 < argc) {
            arg_tokens.emplace_back(argv[++i]);
        } else if (a == "--kernel-bin" && i + 1 < argc) {
            kernel_bins.push_back(parse_kernel_spec(argv[++i]));
        } else if (a == "--aicpu-thread-num" && i + 1 < argc) {
            aicpu_thread_num = std::atoi(argv[++i]);
        } else if (a == "--block-dim" && i + 1 < argc) {
            block_dim = std::atoi(argv[++i]);
        } else if (a == "--orch-thread-num" && i + 1 < argc) {
            orch_thread_num = std::atoi(argv[++i]);
        } else if (a == "--env" && i + 1 < argc) {
            std::string kv(argv[++i]);
            auto eq = kv.find('=');
            if (eq != std::string::npos) {
                env_vars.emplace_back(kv.substr(0, eq), kv.substr(eq + 1));
            }
        }
    }

    if (device_id < 0 || rank < 0 || nranks <= 0 ||
        artifact_dir.empty() || rootinfo_file.empty()) {
        fprintf(stderr,
            "Usage: distributed_worker --device-id N --rank R --nranks N "
            "--artifact-dir PATH --rootinfo-file PATH "
            "--orch-file FILE --orch-func NAME "
            "--kernel-bin ID:FILE "
            "[--win-buffer name:dtype:count] [--dev-buffer name:dtype:count] "
            "[--load name] [--save name] [--arg token] "
            "[--win-sync-prefix bytes] [--data-dir PATH] "
            "[--env KEY=VALUE]\n");
        return 1;
    }

    // Apply environment variables
    for (auto& [k, v] : env_vars) {
        setenv(k.c_str(), v.c_str(), 1);
    }

    if (data_dir.empty()) {
        data_dir = artifact_dir + "/rank_" + std::to_string(rank);
    }

    auto find_buffer = [&](const std::string& name) -> BufferDesc* {
        for (auto& b : buffers) if (b.name == name) return &b;
        return nullptr;
    };

    fprintf(stderr, "[rank %d] Starting: device=%d, nranks=%d, root=%d, "
            "orch=%s::%s, buffers=%zu, args=%zu\n",
            rank, device_id, nranks, root,
            orch_file.c_str(), orch_func.c_str(),
            buffers.size(), arg_tokens.size());

    // ========================================================================
    // Phase 0: Load simpler shared library
    // ========================================================================
    std::string lib_path = artifact_dir + "/libhost_runtime.so";
    void* lib = dlopen(lib_path.c_str(), RTLD_NOW | RTLD_GLOBAL);
    if (!lib) {
        fprintf(stderr, "[rank %d] dlopen failed: %s\n", rank, dlerror());
        return 2;
    }

    auto fn_get_runtime_size = (fn_get_runtime_size_t)dlsym(lib, "get_runtime_size");
    auto fn_set_device       = (fn_set_device_t)dlsym(lib, "set_device");
    auto fn_init_runtime     = (fn_init_runtime_t)dlsym(lib, "init_runtime");
    auto fn_launch_runtime   = (fn_launch_runtime_t)dlsym(lib, "launch_runtime");
    auto fn_finalize_runtime = (fn_finalize_runtime_t)dlsym(lib, "finalize_runtime");

    if (!fn_get_runtime_size || !fn_set_device || !fn_init_runtime ||
        !fn_launch_runtime || !fn_finalize_runtime) {
        fprintf(stderr, "[rank %d] dlsym failed: %s\n", rank, dlerror());
        dlclose(lib);
        return 2;
    }

    // ========================================================================
    // Phase 1: Platform init + device set
    // ========================================================================
    auto backend = create_backend("runtime");

    if (backend->init() != 0) {
        fprintf(stderr, "[rank %d] Platform init failed\n", rank);
        dlclose(lib);
        return 3;
    }

    if (backend->set_device(device_id) != 0) {
        fprintf(stderr, "[rank %d] Platform set_device(%d) failed\n",
                rank, device_id);
        dlclose(lib);
        return 3;
    }
    fprintf(stderr, "[rank %d] Device %d set\n", rank, device_id);

    // ========================================================================
    // Phase 2: Communication init + resource allocation
    // ========================================================================
    if (backend->comm_init(nranks, rank, rootinfo_file, artifact_dir) != 0) {
        fprintf(stderr, "[rank %d] comm_init failed\n", rank);
        dlclose(lib);
        return 3;
    }
    fprintf(stderr, "[rank %d] Communication initialized\n", rank);

    if (backend->comm_alloc_resources() != 0) {
        fprintf(stderr, "[rank %d] comm_alloc_resources failed\n", rank);
        dlclose(lib);
        return 3;
    }

    const auto& hostCtx = backend->get_host_context();
    auto* deviceCtx = backend->get_device_context();

    fprintf(stderr, "[rank %d] Context: rankId=%u, rankNum=%u, winSize=%lu\n",
            rank, hostCtx.rankId, hostCtx.rankNum, hostCtx.winSize);
    for (uint32_t i = 0; i < hostCtx.rankNum && i < HCCL_MAX_RANK_NUM; ++i) {
        fprintf(stderr, "[rank %d]   windowsIn[%u] = 0x%lx\n",
                rank, i, hostCtx.windowsIn[i]);
    }

    // ========================================================================
    // Phase 3: Buffer allocation + file loading
    // ========================================================================
    uint64_t localWinBase = hostCtx.windowsIn[rank];
    size_t winOffset = 0;
    if (nranks > 1 && win_sync_prefix > 0) {
        WindowAlloc(localWinBase, winOffset, win_sync_prefix);
    }

    for (auto& buf : buffers) {
        if (buf.placement == "window") {
            buf.dev_ptr = WindowAlloc(localWinBase, winOffset, buf.bytes());
        } else {
            if (backend->malloc_device(&buf.dev_ptr, buf.bytes()) != 0) {
                fprintf(stderr, "[rank %d] malloc_device '%s' (%zu bytes) failed\n",
                        rank, buf.name.c_str(), buf.bytes());
                return 3;
            }
        }
        fprintf(stderr, "[rank %d] Buffer '%s': %s %zu x %s = %zu bytes @ %p\n",
                rank, buf.name.c_str(), buf.placement.c_str(),
                buf.count, buf.dtype.c_str(), buf.bytes(), buf.dev_ptr);
    }

    for (auto& name : load_names) {
        auto *buf = find_buffer(name);
        if (!buf) {
            fprintf(stderr, "[rank %d] --load: buffer '%s' not found\n",
                    rank, name.c_str());
            return 1;
        }
        std::string path = data_dir + "/" + name + ".bin";
        auto host_data = read_file(path);
        if (host_data.empty()) {
            fprintf(stderr, "[rank %d] Failed to read %s\n", rank, path.c_str());
            return 2;
        }
        if (host_data.size() != buf->bytes()) {
            fprintf(stderr, "[rank %d] Size mismatch '%s': file=%zu, expected=%zu\n",
                    rank, name.c_str(), host_data.size(), buf->bytes());
            return 2;
        }

        // For onboard: h2d copy needs staging through device memory
        // For sim: h2d is just memcpy, no staging needed
        void *staging = nullptr;
        if (backend->malloc_device(&staging, buf->bytes()) != 0) {
            fprintf(stderr, "[rank %d] malloc staging '%s' failed\n",
                    rank, name.c_str());
            return 3;
        }
        backend->memcpy_h2d(staging, host_data.data(), buf->bytes());
        backend->memcpy_d2d(buf->dev_ptr, staging, buf->bytes());
        backend->free_device(staging);
        fprintf(stderr, "[rank %d] Loaded '%s' from %s (%zu bytes)\n",
                rank, name.c_str(), path.c_str(), host_data.size());
    }

    backend->comm_barrier();

    // ========================================================================
    // Phase 4: Kernel execution via simpler runtime
    // ========================================================================
    {
    int rc = fn_set_device(device_id);
    if (rc != 0) {
        fprintf(stderr, "[rank %d] simpler set_device failed: %d\n", rank, rc);
        dlclose(lib);
        return 4;
    }

    auto orch_so  = read_file(artifact_dir + "/" + orch_file);
    auto aicpu_so = read_file(artifact_dir + "/libaicpu_kernel.so");
    auto aicore_o = read_file(artifact_dir + "/aicore_kernel.o");

    if (orch_so.empty() || aicpu_so.empty() || aicore_o.empty()) {
        fprintf(stderr, "[rank %d] Failed to load runtime artifacts from %s\n",
                rank, artifact_dir.c_str());
        dlclose(lib);
        return 2;
    }

    std::vector<std::vector<uint8_t>> k_data(kernel_bins.size());
    std::vector<int> k_func_ids(kernel_bins.size());
    std::vector<const uint8_t*> k_ptrs(kernel_bins.size());
    std::vector<size_t> k_sizes(kernel_bins.size());
    for (size_t ki = 0; ki < kernel_bins.size(); ++ki) {
        k_data[ki] = read_file(artifact_dir + "/" + kernel_bins[ki].filename);
        if (k_data[ki].empty()) {
            fprintf(stderr, "[rank %d] Failed to load kernel %s\n",
                    rank, kernel_bins[ki].filename.c_str());
            dlclose(lib);
            return 2;
        }
        k_func_ids[ki] = kernel_bins[ki].func_id;
        k_ptrs[ki] = k_data[ki].data();
        k_sizes[ki] = k_data[ki].size();
    }

    // Assemble args from --arg tokens
    std::vector<uint64_t> func_args;
    for (auto& tok : arg_tokens) {
        if (tok == "nranks") {
            func_args.push_back(static_cast<uint64_t>(nranks));
        } else if (tok == "root") {
            func_args.push_back(static_cast<uint64_t>(root));
        } else if (tok == "deviceCtx") {
            func_args.push_back(reinterpret_cast<uint64_t>(deviceCtx));
        } else {
            auto *buf = find_buffer(tok);
            if (!buf) {
                fprintf(stderr, "[rank %d] --arg: unknown token '%s'\n",
                        rank, tok.c_str());
                dlclose(lib);
                return 1;
            }
            func_args.push_back(reinterpret_cast<uint64_t>(buf->dev_ptr));
        }
    }

    int n_args = static_cast<int>(func_args.size());
    std::vector<int> arg_types(n_args, 0);
    std::vector<uint64_t> arg_sizes(n_args, 0);

    size_t rt_size = fn_get_runtime_size();
    void* runtime = std::malloc(rt_size);
    if (!runtime) {
        fprintf(stderr, "[rank %d] malloc runtime failed\n", rank);
        dlclose(lib);
        return 4;
    }

    fprintf(stderr, "[rank %d] Initializing simpler runtime (%d args, %zu kernels) ...\n",
            rank, n_args, kernel_bins.size());
    rc = fn_init_runtime(runtime,
        orch_so.data(), orch_so.size(), orch_func.c_str(),
        func_args.data(), n_args, arg_types.data(), arg_sizes.data(),
        k_func_ids.data(), k_ptrs.data(), k_sizes.data(),
        static_cast<int>(kernel_bins.size()));

    if (rc != 0) {
        fprintf(stderr, "[rank %d] simpler init_runtime failed: %d\n", rank, rc);
        std::free(runtime);
        dlclose(lib);
        return 4;
    }

    fprintf(stderr, "[rank %d] Launching kernel "
            "(aicpu_threads=%d, block_dim=%d, orch_threads=%d) ...\n",
            rank, aicpu_thread_num, block_dim, orch_thread_num);
    rc = fn_launch_runtime(runtime,
        aicpu_thread_num, block_dim, device_id,
        aicpu_so.data(), aicpu_so.size(),
        aicore_o.data(), aicore_o.size(), orch_thread_num);

    if (rc != 0) {
        fprintf(stderr, "[rank %d] simpler launch_runtime failed: %d\n", rank, rc);
        std::free(runtime);
        dlclose(lib);
        return 4;
    }

    rc = fn_finalize_runtime(runtime);
    if (rc != 0) {
        fprintf(stderr, "[rank %d] simpler finalize_runtime failed: %d\n", rank, rc);
        std::free(runtime);
        dlclose(lib);
        return 4;
    }
    std::free(runtime);
    }

    fprintf(stderr, "[rank %d] Kernel execution complete\n", rank);
    backend->comm_barrier();

    // ========================================================================
    // Phase 5: Save output buffers
    // ========================================================================
    for (auto& name : save_names) {
        auto *buf = find_buffer(name);
        if (!buf) {
            fprintf(stderr, "[rank %d] --save: buffer '%s' not found\n",
                    rank, name.c_str());
            continue;
        }
        std::vector<uint8_t> host_data(buf->bytes());
        if (backend->memcpy_d2h(host_data.data(), buf->dev_ptr,
                                 buf->bytes()) != 0) {
            fprintf(stderr, "[rank %d] Copy back '%s' failed\n",
                    rank, name.c_str());
            continue;
        }
        std::string path = data_dir + "/" + name + ".bin";
        if (write_file(path, host_data.data(), host_data.size())) {
            fprintf(stderr, "[rank %d] Saved '%s' to %s (%zu bytes)\n",
                    rank, name.c_str(), path.c_str(), host_data.size());
        }
    }

    // ========================================================================
    // Phase 6: Cleanup
    // ========================================================================
    for (auto& buf : buffers) {
        if (buf.placement == "device" && buf.dev_ptr) {
            backend->free_device(buf.dev_ptr);
        }
    }
    dlclose(lib);
    backend->comm_destroy();
    backend->reset_device(device_id);
    backend->finalize();

    fprintf(stderr, "[rank %d] Done\n", rank);
    return 0;
}
